language: cpp

os:
  - linux
  - windows

git:
  depth: 1

services:
  - docker

env:
  global:
    - _C=build
    - WORKDIR=/spelunky
    - BUILD_IMAGE=dbeef/spelunky-psp

stages:
  - build
  - name: deploy
    if: tag is present

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run -it -d --volume `pwd`:$WORKDIR --name $_C $BUILD_IMAGE /bin/bash ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' ; fi
  - mkdir -p install

jobs:
  exclude:
    - stage: test
  include:
  - stage: build
    os: linux
    name: "Build PSP"
    script:
      - docker exec -w $WORKDIR $_C /bin/bash -c "./scripts/config-psp.sh ; ./scripts/build-psp.sh"
      - cp tmp/build-psp/EBOOT.PBP install/Spelunky_PSP.pbp
  - name: "Build Linux"
    os: linux
    script:
      - docker exec -w $WORKDIR $_C /bin/bash -c "./scripts/config-linux.sh ; ./scripts/build-linux.sh"
      - cp tmp/install-linux/Release/bin/Spelunky_PSP install/Spelunky_PSP_Linux
  - name: "Build Android"
    os: linux
    script:
      - docker exec -w $WORKDIR $_C /bin/bash -c "./scripts/build-android.sh"
      - cp tmp/install-android/Spelunky_PSP.apk install/Spelunky_PSP_Android.apk
  - name: "Build Windows"
    os: windows
    script:
      - powershell -File ./scripts/dependencies-install.ps1
      - powershell -File ./scripts/config-windows.ps1
      - powershell -File ./scripts/build-windows.ps1
      - 7z a -sdel install/SpelunkyWindows.zip ./tmp/install-windows/Release/bin/*

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: install/Spelunky*
  skip_cleanup: true
  on:
    tags: true
