project(Prefabs)

add_library(Prefabs STATIC
        interface/prefabs/effects/Explosion.hpp
        interface/prefabs/effects/ShotgunBlast.hpp
        interface/prefabs/collectibles/SingleGoldBar.hpp
        interface/prefabs/collectibles/TripleGoldBar.hpp
        interface/prefabs/collectibles/BigGem.hpp
        interface/prefabs/collectibles/SmallGem.hpp
        interface/prefabs/collectibles/GoldChunk.hpp
        interface/prefabs/collectibles/GoldNugget.hpp
        interface/prefabs/ui/DeathOverlay.hpp
        interface/prefabs/ui/HudIcon.hpp
        interface/prefabs/ui/HudOverlay.hpp
        interface/prefabs/ui/PauseOverlay.hpp
        interface/prefabs/ui/TileBrowserWindow.hpp
        interface/prefabs/ui/Text.hpp
        interface/prefabs/ui/CheatConsoleWindow.hpp
        interface/prefabs/ui/ScoresOverlay.hpp
        interface/prefabs/ui/LevelSummaryOverlay.hpp
        interface/prefabs/items/Jetpack.hpp
        interface/prefabs/items/Compass.hpp
        interface/prefabs/items/Arrow.hpp
        interface/prefabs/items/Flare.hpp
        interface/prefabs/items/GoldenIdol.hpp
        interface/prefabs/items/Glove.hpp
        interface/prefabs/items/RopeChainElement.hpp
        interface/prefabs/items/Chest.hpp
        interface/prefabs/items/Rock.hpp
        interface/prefabs/items/Jar.hpp
        interface/prefabs/items/Shotgun.hpp
        interface/prefabs/items/Bomb.hpp
        interface/prefabs/items/Mitt.hpp
        interface/prefabs/items/Pistol.hpp
        interface/prefabs/items/Skull.hpp
        interface/prefabs/items/BombBag.hpp
        interface/prefabs/items/RopeSpawner.hpp
        interface/prefabs/items/Whip.hpp
        interface/prefabs/items/SpikeShoes.hpp
        interface/prefabs/items/Rope.hpp
        interface/prefabs/items/SpringShoes.hpp
        interface/prefabs/items/Wallet.hpp
        interface/prefabs/items/BombSpawner.hpp
        interface/prefabs/items/Crate.hpp
        interface/prefabs/items/RopePile.hpp
        interface/prefabs/items/Cape.hpp
        interface/prefabs/npc/DamselStates.hpp
        interface/prefabs/npc/ShopkeeperScript.hpp
        interface/prefabs/npc/Snake.hpp
        interface/prefabs/npc/Skeleton.hpp
        interface/prefabs/npc/CavemanStates.hpp
        interface/prefabs/npc/RedFrog.hpp
        interface/prefabs/npc/Spider.hpp
        interface/prefabs/npc/CavemanScript.hpp
        interface/prefabs/npc/DamselScript.hpp
        interface/prefabs/npc/ShopkeeperStates.hpp
        interface/prefabs/npc/Caveman.hpp
        interface/prefabs/npc/Shopkeeper.hpp
        interface/prefabs/npc/Damsel.hpp
        interface/prefabs/npc/BlueFrog.hpp
        interface/prefabs/npc/Bat.hpp
        interface/prefabs/npc/FakeSkeleton.hpp
        interface/prefabs/particles/ItemCollectedParticle.hpp
        interface/prefabs/particles/RopeCollectedParticle.hpp
        interface/prefabs/particles/BloodParticle.hpp
        interface/prefabs/particles/HelpParticle.hpp
        interface/prefabs/particles/SmokePuffParticle.hpp
        interface/prefabs/particles/PoofParticle.hpp
        interface/prefabs/particles/BonesParticle.hpp
        interface/prefabs/particles/RubbleSmallParticle.hpp
        interface/prefabs/particles/FlareSparkParticle.hpp
        interface/prefabs/particles/FlameParticle.hpp
        interface/prefabs/particles/BigCollectParticle.hpp
        interface/prefabs/particles/FlameTrailParticle.hpp
        interface/prefabs/particles/BloodTrailParticle.hpp
        interface/prefabs/particles/BombCollectedParticle.hpp
        interface/prefabs/particles/RotatingDollarParticle.hpp
        interface/prefabs/particles/SmoochingParticle.hpp
        interface/prefabs/other/Bones.hpp
        interface/prefabs/other/Bullet.hpp
        interface/prefabs/traps/Spikes.hpp
        interface/prefabs/traps/ArrowTrap.hpp
        interface/prefabs/props/MainLogo.hpp
        interface/prefabs/props/TutorialSign.hpp
        interface/prefabs/props/StartSign.hpp
        interface/prefabs/props/ResetSign.hpp
        interface/prefabs/props/CopyrightsSign.hpp
        interface/prefabs/props/QuitSign.hpp
        interface/prefabs/props/ScoresSign.hpp
        interface/prefabs/props/GithubLink.hpp
        interface/prefabs/main-dude/MainDude.hpp
        src/prefabs/props/GithubLink.cpp
        src/prefabs/props/ScoresSign.cpp
        src/prefabs/props/QuitSign.cpp
        src/prefabs/props/StartSign.cpp
        src/prefabs/props/MainLogo.cpp
        src/prefabs/props/TutorialSign.cpp
        src/prefabs/props/CopyrightsSign.cpp
        src/prefabs/props/ResetSign.cpp
        src/prefabs/other/Bullet.cpp
        src/prefabs/other/Bones.cpp
        src/prefabs/effects/ShotgunBlast.cpp
        src/prefabs/effects/Explosion.cpp
        src/prefabs/traps/Spikes.cpp
        src/prefabs/traps/ArrowTrap.cpp
        src/prefabs/ui/HudOverlay.cpp
        src/prefabs/ui/Text.cpp
        src/prefabs/ui/LevelSummaryOverlay.cpp
        src/prefabs/ui/TileBrowserWindow.cpp
        src/prefabs/ui/PauseOverlay.cpp
        src/prefabs/ui/CheatConsoleWindow.cpp
        src/prefabs/ui/DeathOverlay.cpp
        src/prefabs/ui/ScoresOverlay.cpp
        src/prefabs/ui/HudIcon.cpp
        src/prefabs/main-dude/MainDude.cpp
        src/prefabs/items/GoldenIdol.cpp
        src/prefabs/items/Skull.cpp
        src/prefabs/items/Whip.cpp
        src/prefabs/items/Compass.cpp
        src/prefabs/items/Pistol.cpp
        src/prefabs/items/Jetpack.cpp
        src/prefabs/items/Shotgun.cpp
        src/prefabs/items/Chest.cpp
        src/prefabs/items/Glove.cpp
        src/prefabs/items/Cape.cpp
        src/prefabs/items/Flare.cpp
        src/prefabs/items/Rope.cpp
        src/prefabs/items/Arrow.cpp
        src/prefabs/items/Crate.cpp
        src/prefabs/items/Wallet.cpp
        src/prefabs/items/Rock.cpp
        src/prefabs/items/RopePile.cpp
        src/prefabs/items/SpringShoes.cpp
        src/prefabs/items/SpikeShoes.cpp
        src/prefabs/items/BombBag.cpp
        src/prefabs/items/BombSpawner.cpp
        src/prefabs/items/Bomb.cpp
        src/prefabs/items/Mitt.cpp
        src/prefabs/items/Jar.cpp
        src/prefabs/items/RopeSpawner.cpp
        src/prefabs/items/RopeChainElement.cpp
        src/prefabs/collectibles/SmallGem.cpp
        src/prefabs/collectibles/BigGem.cpp
        src/prefabs/collectibles/GoldNugget.cpp
        src/prefabs/collectibles/GoldChunk.cpp
        src/prefabs/collectibles/TripleGoldBar.cpp
        src/prefabs/collectibles/SingleGoldBar.cpp
        src/prefabs/npc/Skeleton.cpp
        src/prefabs/npc/CavemanScript.cpp
        src/prefabs/npc/DamselScript.cpp
        src/prefabs/npc/Caveman.cpp
        src/prefabs/npc/ShopkeeperScript.cpp
        src/prefabs/npc/ShopkeeperStates.cpp
        src/prefabs/npc/CavemanStates.cpp
        src/prefabs/npc/DamselStates.cpp
        src/prefabs/npc/Damsel.cpp
        src/prefabs/npc/FakeSkeleton.cpp
        src/prefabs/npc/Shopkeeper.cpp
        src/prefabs/npc/RedFrog.cpp
        src/prefabs/npc/Snake.cpp
        src/prefabs/npc/Spider.cpp
        src/prefabs/npc/Bat.cpp
        src/prefabs/npc/BlueFrog.cpp
        src/prefabs/particles/BloodTrailParticle.cpp
        src/prefabs/particles/SmoochingParticle.cpp
        src/prefabs/particles/FlameParticle.cpp
        src/prefabs/particles/ItemCollectedParticle.cpp
        src/prefabs/particles/RopeCollectedParticle.cpp
        src/prefabs/particles/PoofParticle.cpp
        src/prefabs/particles/HelpParticle.cpp
        src/prefabs/particles/FlameTrailParticle.cpp
        src/prefabs/particles/FlareSparkParticle.cpp
        src/prefabs/particles/BigCollectParticle.cpp
        src/prefabs/particles/RubbleSmallParticle.cpp
        src/prefabs/particles/RotatingDollarParticle.cpp
        src/prefabs/particles/SmokePuffParticle.cpp
        src/prefabs/particles/BloodParticle.cpp
        src/prefabs/particles/BonesParticle.cpp
        src/prefabs/particles/BombCollectedParticle.cpp
)

target_include_directories(Prefabs
        PRIVATE interface interface
        INTERFACE interface
)

set_target_properties(Prefabs PROPERTIES
        CXX_STANDARD
        17
)

target_link_libraries(Prefabs
        PUBLIC
        Patterns
        EntityRegistry
        Components
        Events
        GameLoop
        Dependencies
        PRIVATE
        Logger
        Audio
        cjson
        $<IF:$<BOOL:${SPELUNKY_PSP_WITH_IMGUI}>,imgui,> # FIXME
)

if (SPELUNKY_PSP_PLATFORM_LINUX)
    target_link_libraries(Prefabs PRIVATE dl)
    target_compile_definitions(Prefabs PRIVATE SPELUNKY_PSP_PLATFORM_LINUX)
elseif (SPELUNKY_PSP_PLATFORM_PSP)
    target_compile_definitions(Prefabs PRIVATE SPELUNKY_PSP_PLATFORM_PSP)
endif ()
