#pragma once

#include <cstdint>

enum class HUDSpritesheetFrames : std::uint16_t
{
    ARROW_ICON = 0,
    BOMB_ICON,
    CAPE_ICON,
    COMPASS_ICON,
    DOLLAR_SIGN,
    GLOVES_ICON,
    HEART,
    HOLD_ITEM_ICON,
    JETPACK_ICON,
    MITT_ICON,
    PARACHUTE_ICON,
    ROPE_ICON,
    SPECTACLES_ICON,
    SPIKE_SHOES_ICON,
    SPRING_SHOES_ICON,
    STICKY_BOMB_ICON,
    HALF_OPAQUE_TILE,
    COMPASS_ARROW_DOWN,
    COMPASS_ARROW_LEFT,
    COMPASS_ARROW_RIGHT,
    COMPASS_ARROW_LEFT_BOTTOM,
    COMPASS_ARROW_RIGHT_BOTTOM,
};
