name: Build, publish - The web artifact
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'recursive'
    - name: Build in Docker container
      uses: addnab/docker-run-action@v2
      with:
        options: --volume ${{ github.workspace }}:/spelunky --workdir /spelunky
        image: emscripten/emsdk
        shell: bash
        run: cd scripts && ./config-emscripten.sh && ./build-emscripten.sh
    - name: Push to Github pages
      run: |

          git config --global user.name "Daniel 'dbeef' Zalega - Github Workflows"
          git config --global user.email "daniel.zalega@gmail.com"

          git checkout github-pages
          cp tmp/build-emscripten/Spelunky_PSP.* artifacts/
          git commit -m "Updated the web build artifact"

          git push --set-upstream origin github-pages
